### ISSUE TITLE
Add a default image for blogpost and profile 

### ISSUE THREAD

**Issue by dannycolin** [OpenScienceMOOC/site#52]
**Describe the bug**

A empty space or the alt text is visible if a blogpost or a profile don't have an image.

**Expected behavior**
If a blogpost or profile don't have an image, there should be a default image inserted as a fallback.

**Tasks**

- [x] Detect if a file exists
- [x] Add a fallback image for blogpost on blog/homepage
- [x] Add a fallback image for people's avatar

**Comment by dannycolin** [comment]
Done.
